#!/bin/bash

if [ -f $BUGZILLA_ROOT/needs_configure ]
then
  cat <<EOF > /checksetup_answers.txt
\$answer{'ADMIN_EMAIL'} = '$ADMIN_EMAIL'; 
\$answer{'ADMIN_OK'} = 'Y';
\$answer{'ADMIN_PASSWORD'} = '$ADMIN_PASSWORD';
\$answer{'ADMIN_REALNAME'} = 'Admin';
\$answer{'NO_PAUSE'} = 1;
\$answer{'create_htaccess'} = '';
\$answer{'cvsbin'} = '/usr/bin/cvs';
\$answer{'db_check'} = 1;
\$answer{'db_driver'} = '$BUGS_DB_DRIVER';
\$answer{'db_host'} = '$BUGS_DB_HOST';
\$answer{'db_name'} = '$BUGS_DB_NAME',
\$answer{'db_pass'} = '$BUGS_DB_PASS';
\$answer{'db_port'} = 0;
\$answer{'db_sock'} = '';
\$answer{'db_user'} = '$BUGS_DB_USER';
\$answer{'diffpath'} = '/usr/bin';
\$answer{'index_html'} = 0;
\$answer{'interdiffbin'} = '/usr/bin/interdiff';
\$answer{'memcached_servers'} = "localhost:11211";
\$answer{'urlbase'} = '$BUGS_CONTEXT/bugzilla/';
\$answer{'use_suexec'} = '';
\$answer{'webservergroup'} = 'bugzilla';
EOF

  cd $BUGZILLA_ROOT

  perl checksetup.pl /checksetup_answers.txt
  perl checksetup.pl /checksetup_answers.txt

  if [ $? = 0 ]
  then
    rm $BUGZILLA_ROOT/needs_configure
  fi
fi

#manually start supervisord
/usr/bin/supervisord -c /etc/supervisord.conf
